/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javafx.scene.media.MediaView;
import javafx.stage.Stage;

public class App extends Application {

  private static final String STREAM_1080P_URL =
    "https://tastytradepublicmedia.s3.amazonaws.com/livestream-playlist-1080.m3u8";

  private static final String STREAM_480P_URL =
    "https://tastytradepublicmedia.s3.amazonaws.com/livestream-playlist.m3u8";

  private boolean use1080 = true;

  private Label status = new Label();

  @Override
  public void start(Stage primaryStage) {
    var pane = new StackPane();

    pane.getChildren().setAll(createMediaView(), status);

    var scene = new Scene(pane, 1024, 768);
    primaryStage.setScene(scene);
    primaryStage.show();
  }

  private MediaView createMediaView() {
    var mediaView = new MediaView();
    mediaView.setPreserveRatio(true);
    mediaView.setSmooth(true);
    mediaView.setOnError(event -> {
      status.setText("Error: " + event.getMediaError());
    });
    initMediaPlayer(mediaView);

    mediaView.setOnMouseClicked(event -> {
      event.consume();

      use1080 = !use1080;

      mediaView.getMediaPlayer().dispose();

      initMediaPlayer(mediaView);
    });


    return mediaView;
  }

  private void initMediaPlayer(MediaView mediaView) {
    status.setText(use1080 ? "1080p" : "480p");
    final var mediaPlayer = new MediaPlayer(new Media(getStreamUrl()));
    mediaPlayer.setAutoPlay(true);
    mediaPlayer.setVolume(0.25);
    mediaView.setMediaPlayer(mediaPlayer);
  }

  public String getStreamUrl() {
    return use1080 ? STREAM_1080P_URL : STREAM_480P_URL;
  }
}
